### ISSUE TITLE
Getting error when index.ts is run

### ISSUE THREAD

**Issue by tzack1** [firefly-sol/jupiter-arb#2]
downloaded the files and installed packages, after all package related errors where fixed, got this error:

if (typeof source !== 'string') { throw new TypeError('Expected String') }
                                            ^
TypeError: Expected String
    at decodeUnsafe (C:\wamp64\www\solanabot\node_modules\base-x\src\index.js:66:45)
    at Object.decode (C:\wamp64\www\solanabot\node_modules\base-x\src\index.js:109:18)

Is there something I am missing to run the application?

**Comment by johncdoubleu** [comment]
Haven't tried it myself yet, but could it be the .env file your missing with the constant for SECRET_KEY?

**Comment by JussCubs** [comment]
I am also getting the same. Must be part of the puzzle, lmk if you fixed it..

**Comment by LenBob2021** [comment]
HAve you guys set up your .env file?

**Comment by Juanba98** [comment]
You must create a ".env" file and store your SECRET_KEY variable. 
https://docs.jup.ag/jupiter-core/full-guide#4.-load-jupiter-instance-and-setup-your-wallet
